### ISSUE TITLE
Suggestion Let me see my aliases

### ISSUE THREAD

**Issue by kabouter** [mozilla/fx-private-relay-add-on#79] opened 2021-04-08 08:13 UTC
I used all my aliases. The add-on pop is so useless. Let me pick one of my existing aliases.
![image](https://user-images.githubusercontent.com/6320511/113991930-3c852b80-9853-11eb-96c1-924a06a24acd.png)

I hope when this releases I can buy more aliases. Or let them expire automatically after a few months.

**Comment by aarek-eng** [comment] 2021-06-23 17:09
Came here to ask for exactly this. The button is practically useless once one has used up all of one's aliases. What would be very, very welcome is the possibility to select them quickly from a context menu, depending on the type of site one is working on.

**Comment by maxxcrawford** [comment] 2021-12-10 03:37
Hey there! [Our next release](https://github.com/mozilla/fx-private-relay-add-on/releases/tag/2.1.1) has a feature where you can right-click and select from recently created aliases to auto-fill a form. 

Closing this specific issue as it's a duplicate of #58.

**Closed by maxxcrawford** 2021-12-10 03:37 UTC
