### ISSUE TITLE
enhancement: mobile addon support missing

### ISSUE THREAD

**Issue by jrconlin** [mozilla/fx-private-relay-add-on#430] opened 2022-11-02 16:53 UTC
Many customers only have a mobile device, or use a mobile device preferably to a desktop or larger format device. It would be useful to have similar features available on Fenix, (ability to quickly generate a masked email, or insert the mask phone number on forms.)

**Comment by cadeyrn** [comment] 2022-11-02 22:30
Duplicate of #391.

**Comment by Vinnl** [comment] 2022-11-03 07:49
Thanks for triaging, I'll close this to keep discussion contained to that issue.

**Closed by Vinnl** 2022-11-03 07:49 UTC
