### ISSUE TITLE
Label from previous entry showing in web-app after creating alias from firefox add-on

### ISSUE THREAD

**Issue by Oryoro** [mozilla/fx-private-relay-add-on#266] opened 2022-01-15 18:13 UTC
I created an alias with the browser plugin. When I looked on the web-app, the label was displaying a duplication of the label belonging to the preceeding alias. I was able to 'remedy' this by simply creating another blank alias in the web-app: then the name of the site I was on when I created the alias appeared in the label field instead, so I'm assuming the correct information was sent and saved in to the remote database. Refreshing the page had no effect.

I wondered if anyone had experienced the same. Could it have been some conflict with data that is stored in the add-on compared to what is stored in the firefox-relay database? If it happens again I'll try and jot down more details.

**Edit (16-Jan-22):** This happened again this morning while trying to change my email address on a site. It populated the Label from my previous entry in to the new label field, instead of the domain name of the site. This time, I accidentaly clicked in to the label, and it saved the incorrect information along with the alias. This is pretty bad and could lead to a lot of confusion. I also noticed an exclamation mark in the Firefox Relay addon's icon in firefox just before this started happening again. It is happening every time I create an alias now.

**Edit:** This happened again. This time I had two browser tabs open with Firefox Relay. One tab was affected and the other wasn't. Again, refreshing the tab didn't help. But, closing and opening a fresh tab did. So it seems like there is some problem with the way the web-page is being rendered.

**Comment by maxxcrawford** [comment] 2022-01-25 16:40
Duplicate of #228. Thank you for report, @Oryoro

**Closed by maxxcrawford** 2022-01-25 16:40 UTC
